spring:
  profiles:
    active: dev
  application:
    name: Digital Village Service Hub
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  mvc:
    problemdetails:
      enabled: true
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  thymeleaf:
    cache: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
server:
  error:
    include-message: always
    include-binding-errors: always
logging:
  level:
    root: INFO
    com.digitalvillage: INFO
